version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: chess_anticheat
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_DB: chess_behavioral
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5433:5432"

volumes:
  pgdata: