global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'chess-anticheat'
    static_configs:
      - targets: ['move-analysis:8000', 'behavioral-analysis:8001', 'engine-service:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']