name: Development Workflow

on:
  push:
    branches: [ develop, feature/**, bugfix/** ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt

      - name: Run linters
        run: |
          black --check .
          isort --check-only .
          flake8 .

      - name: Run tests
        run: |
          pytest tests/ --cov=services

      - name: Check type hints
        run: |
          mypy services/

  integration-tests:
    needs: validate
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Run integration tests
        run: |
          pytest tests/integration/

  build:
    needs: [validate, integration-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          docker-compose build